# Generated by Django 2.1.5 on 2019-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio_len',
            field=models.FloatField(default=0),
        ),
    ]
