# Generated by Django 2.1.5 on 2019-06-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0003_auto_20190602_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='music_count',
            field=models.IntegerField(default=0),
        ),
    ]
