# Generated by Django 2.1.5 on 2019-06-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0004_artist_music_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='nick_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
