# Generated by Django 2.1.5 on 2019-06-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0005_auto_20190602_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='nick_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
