# Generated by Django 2.1.5 on 2019-07-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0009_video_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio',
            field=models.FileField(upload_to=''),
        ),
    ]
