# Generated by Django 2.1.5 on 2019-07-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0010_auto_20190701_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='music_count',
        ),
    ]
