# Generated by Django 2.1.5 on 2019-07-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0011_remove_artist_music_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Аты'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Жөні'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nick_name',
            field=models.CharField(max_length=255, verbose_name='Лақап аты'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Атауы'),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music_portal.Artist', verbose_name='Әнші'),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio',
            field=models.FileField(upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music_portal.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Әнін жазған'),
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Атауы'),
        ),
        migrations.AlterField(
            model_name='music',
            name='word_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cөзін жазған'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Түсіндірме'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Атауы'),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Сілтеме'),
        ),
    ]
